In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print(arr_1d)


[1 2 3 4 5]


In [8]:
# creating 2d array
arr_2d = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
# creating arrray with zeros, ones, full, range or specific value
arr_zeros = np.zeros((2,2))
print(arr_zeros)

[[0. 0.]
 [0. 0.]]


In [10]:
# creating array with ones 
arr_ones = np.ones((3,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# creating array with full 
arr_full = np.full((2,3),7)
print(arr_full)

[[7 7 7]
 [7 7 7]]


In [12]:
# creating array with a range of values
arr_range = np.arange(0, 10, 2)
print(arr_range)

[0 2 4 6 8]


In [17]:
#creating the arrayy with evenly spaced vcalues
arr_linespace = np.linspace(0, 1, 5)
print(arr_linespace)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Array Operations
